# Generated by Django 4.1.9 on 2023-06-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_followercount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstnm',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastnm',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
