# Generated by Django 4.1.9 on 2023-06-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='profile-icon-login-head-icon-vector.jpg', upload_to='profile_image'),
        ),
    ]
