# Generated by Django 4.1.9 on 2023-06-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='user-6380868_1280.webp', upload_to='profile_image'),
        ),
    ]
